# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  unit_and_integration_tests:
    strategy:
      matrix:
        node-version: [20.x]
    uses: Breizhsport-cesi-pau/breizhsport-infra/.github/workflows/test.unit-integration-back.yml@back/workflow(s)
    with:
      node-version: ${{ matrix.node-version }}
  quality_tests:
    needs: [unit_and_integration_tests]
    uses: Breizhsport-cesi-pau/breizhsport-infra/.github/workflows/test.quality.yml@main
    secrets:
      SONAR_CLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      coverage_folder: ./coverage
      coverage_artifact_name: coverage
  publish_to_docker_push_event:
    needs: [quality_tests, unit_and_integration_tests]
    uses: Breizhsport-cesi-pau/breizhsport-infra/.github/workflows/publish.docker.yml@main
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-user-service:develop
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
    if: github.event_name != 'pull_request'
  publish_to_docker_pr_event:
    needs: [quality_tests, unit_and_integration_tests]
    uses: Breizhsport-cesi-pau/breizhsport-infra/.github/workflows/publish.docker.yml@main
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-user-service:develop-pr-${{ github.event.number }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
    if: github.event_name == 'pull_request'
